name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or 'master' if you're using that

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # change if you're using 6.0 or 7.0

      - name: Restore dependencies
        run: dotnet restore ./CourseHubApi/CourseHubApi.csproj

      - name: Build
        run: dotnet build ./CourseHubApi/CourseHubApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./CourseHubApi/CourseHubApi.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          api_location: "publish"     # this is where we publish our API
          skip_app_build: true        # we don't have a frontend (React etc.)
